[package]
name = "squash_creeps"
version = "0.1.0"
edition = "2021"
rust-version = "1.79"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
