name: build-godot-game
run-name: build-godot-${{ github.sha }}
on: [push]
env:
    GODOT_RUST_WORKSPACE: "${{ github.workspace }}/rust"
    GODOT_RUST_TARGET: "${{ github.workspace }}/target"
jobs:
    setup-godot:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get godot game engine version
              run: |
                GODOT_VERSION=$(cat .godot-version | xargs)
                echo "godot_version=$GODOT_VERSION" >> $GITHUB_OUTPUT

    compile-rust-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
              with:
                workspaces: ${{ env.GODOT_RUST_WORKSPACE }} -> ../target
            - name: Compile godot-rust extension game code
              run: |
                cargo build --manifest-path $GODOT_RUST_WORKSPACE/Cargo.toml --target-dir $GODOT_RUST_TARGET
