name: build-godot-game
run-name: build-godot-${{ github.sha }}
on: [push]
env:
    GODOT_RUST_WORKSPACE: "${{ github.workspace }}/rust"
    GODOT_RUST_TARGET: "${{ github.workspace }}/target"
jobs:
    find-godot-engine-info:
        runs-on: ubuntu-latest
        outputs:
          godot_version: ${{ steps.godot-version.outputs.godot_version }}
          arch: ${{ steps.arch.outputs.arch }}
        steps:
            - uses: actions/checkout@v4
            - name: Find Godot version and system architecture
              id: godot-version
              run: |
                GODOT_VERSION=$(cat .godot-version | xargs)
                echo "Godot Version: $GODOT_VERSION"
                echo "godot_version=$GODOT_VERSION" >> $GITHUB_OUTPUT

            - name: Find system architecture
              id: arch
              run: |
                ARCH=$(uname -m)
                echo "System architecture: $ARCH"
                echo "arch=$ARCH" >> $GITHUB_OUTPUT

    setup-godot-engine:
      runs-on: ubuntu-latest
      needs: [find-godot-engine-info]
      steps:
          - name: Install Godot game engine
            env:
              GODOT_VERSION: ${{ needs.find-godot-engine-info.outputs.godot_version }}
              ARCH: ${{ needs.find-godot-engine-info.outputs.arch }}
            run: |
              mkdir $HOME/godot_engine
              cd $HOME/godot_engine
              wget --verbose -O godot.zip https://github.com/godotengine/godot-builds/releases/download/$GODOT_VERSION-stable/Godot_v$GODOT_VERSION-stable_linux.$ARCH.zip
              unzip godot.zip
              ln -s Godot_v$GODOT_VERSION-stable_linux.$ARCH Godot
              export PATH="$HOME/godot_engine:$PATH"
              Godot --version

    compile-rust-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
              with:
                workspaces: ${{ env.GODOT_RUST_WORKSPACE }} -> ../target
            - name: Compile godot-rust extension game code
              run: |
                cargo build --manifest-path $GODOT_RUST_WORKSPACE/Cargo.toml --target-dir $GODOT_RUST_TARGET
